title: Ahmadxp
description: My personal web using lume deno and tailwind css.
image: =image
url: =url
keywords:
  - web
  - personal web
  - site
  - personal site
  - static site
  - blog
  - ahmadxp
generator: true